#!/usr/bin/env python

import tarfile, json, os
from time import strftime

def create_bzip(directory):
	if os.path.exists(directory + strftime("%m%d%Y") + ".tar.bz2") == True:
		print "\nFile (" + directory + "." + strftime("%m%d%Y") + ".tar.bz2" + ") already exists, do you want to overwrite? [Y/N] ",
		ans = raw_input()
		if ans == "Y" or ans == "y":
			tar = tarfile.open(directory + "." + strftime("%m%d%Y") + ".tar.bz2", "w:bz2")
			tar.add(directory)
		else:
			print "Skipping " + directory
	else:
		tar = tarfile.open(directory + "." + strftime("%m%d%Y") + ".tar.bz2", "w:bz2")
		tar.add(directory)

def main():
	file_contents = open('dugong.json')
	json_parsed = json.load(file_contents)

	for site in json_parsed['site']:
		try:
			if os.path.isdir(site['site_directory']) == True:
				print "Compressing " + site['site_name'] + "...",
				create_bzip(site['site_directory'])
				print " Done"
			else:
				print "Directory " + site['site_directory'] + " does not exist"
		except KeyError, err:
			print "KeyError: " + str(err)
		except ValueError, err:
			print "ValueError: " + str(err)

if __name__ == "__main__":
	main()