#!/usr/bin/env python

import tarfile
import os
import sys
from time import strftime


def create_bzip(directory):
    tar = tarfile.open('{dir}.{timestamp}.tar.bz2'.format(dir=directory, timestamp=strftime('%m%d%Y')), 'w:bz2')
    tar.add(directory)
    print u'{dir} \u2714'.format(dir=directory)


def main():
    cwd = os.getcwd()
    subdirs = os.listdir(cwd)

    for directory in subdirs:
        if 'com.' in directory and not '.bz2' in directory:
            create_bzip(''.join([cwd, '/', directory]))
        elif 'net.' in directory and not '.bz2' in directory:
            create_bzip(''.join([cwd, '/', directory]))
        elif 'org.' in directory and not '.bz2' in directory:
            create_bzip(''.join([cwd, '/', directory]))


if __name__ == '__main__':
    main()
